
module.exports ={
    titleProps:{
        inputName:'title',
        validation:[
            {
                isEmpty:false
            },
            {
                isAlphabets:false
            }
        ]
    },
    contentProperties:{
        inputName:'content',
        validation:[
            {
                isEmpty:false,
            }
        ]
    },
    descProps:{
        inputName:'description',
        validation:[
            {
                isEmpty:false,
            }
        ]
    },
    cardImageProps:{
        inputName:'cardImage',
        validation:[
            {
                isImage:true
            }
        ]
    },
    orientationProps:{
        inputName:'orientation',
        validation:[
            {
                isEmpty:false
            },
        ]
    },
    statusProps:{
        inputName:'status',
        validation:[
            {
                isBoolean:true,
            }
        ]
    },
    slugProperties:{
        inputName:'slug',
        validation:[
            {
                isEmpty:false
            },
            {
                isLength:{min:4}
            }
            ,
            {
                isAlphabets:false,
            },
        ]
    },
}
