
module.exports={
    nameProperties:{
        inputName:'name',
        validation:[
            {
                isEmpty:false
            },
            {
                isLength:{min:3}
            }
            ,
            {
                isAlphabets:true,
            },
        ]
    },
    titleProperties:{
        inputName:'title',
        validation:[
            {
                isEmpty:false
            },
            {
                isLength:{min:5}
            }
            ,
            {
                isAlphabets:true,
            },
        ]
    },
    statusProperties:{
        inputName:'status',
        validation:[
            {
                isBoolean:true
            },
        ]
    },
    slugProperties:{
        inputName:'slug',
        validation:[
            {
                isEmpty:false
            },
            {
                isLength:{min:3}
            }
            ,
            {
                isAlphabets:true,
            },
        ]
    },
    descriptionProperties:{
        inputName:'description',
        validation:[
            {
                isEmpty:false
            }
        ]
    },
    imageProperties:{
        inputName:'collectionImage',
        validation:[
            {
                isImage:true
            }
        ]
    },
    bgColorProperties:{
        inputName:'backgroundColor',
        validation:[
            {
                isValueColor:true
            }
        ]
    },
}