
module.exports ={
    titleProperties:{
        inputName:'title',
        validation:[
            {
                isEmpty:false
            },
            {
                isAlphabets:true
            }
        ]
    },
    descriptionProperties:{
        inputName:'description',
        validation:[
            {
                isEmpty:false,
            }
        ]
    },
    invitationImageProperties:{
        inputName:'invitationImage',
        validation:[
            {
                isImage:true
            }
        ]
    },
    invitationSizeProperties:{
        inputName:'invitationSize',
        validation:[
            {
                isEmpty:false
            }
        ]
    },
    statusProperties:{
        inputName:'status',
        validation:[
            {
                isBoolean:true,
            }
        ]
    },
    slugProperties:{
        inputName:'slug',
        validation:[
            {
                isEmpty:false
            },
            {
                isLength:{min:4}
            }
            ,
            {
                isAlphabets:true,
            },
        ]
    },
    bgColorProperties:{
        inputName:'backgroundColor',
        validation:[
            {
                isValueColor:true
            }
        ]
    },
}
